### ISSUE TITLE
Is it possible to hide the tooltip?

### ISSUE THREAD

**Issue by tyzion** [ambassify/react-avatar#238] opened 2022-05-06 13:52 UTC
Hi guys!

I've tried to get and find the tooltip element with the name and surname, but couldn't.
Is there a way to hide it or/and not show it?

**Comment by JorgenEvens** [comment] 2022-06-01 07:49
Duplicate of https://github.com/ambassify/react-avatar/pull/241

Will be fixed in the 5.0.0 release I'm preparing right now.

**Closed by JorgenEvens** 2022-06-01 07:49 UTC

**Comment by JorgenEvens** [comment] 2022-06-01 11:37
Hi @tyzion,

This is now possible in the [5.0.0](https://github.com/ambassify/react-avatar/releases/tag/v5.0.0) release of react-avatar by setting the `title` property to `false` or `null`.
